### ISSUE TITLE
Replace D5 and D6 for a single higher forward current diode

### ISSUE THREAD

**Issue by henrique-silva** [lnls-dig/afc-hw#14]
The SS16 schottky diode has a forward current limit set in 1A, which is less than needed for the AFC board fully operate with both FMC connected when powered from the ATX stand-alone connector.

Using 2 diodes in parallel is dangerous because if they have a slight unbalacing, one of them will start to drive more current and, consequently, heat more. The heating in a diode makes it drive even more current, resulting in a positive current feedback that ends with the diode burning up.

**Comment by aylons** [comment]
I agree.

To substitute it, I suggest a diode from this list:

http://www.digikey.com/product-search/en/discrete-semiconductor-products/diodes-rectifiers-single/1376383?k=&pkeyword=&pv1291=2025&pv1291=7351&pv1291=2050&FV=1140003%2Ce480002%2Ce480006%2Ce480009%2Ce480014%2Ce48001c%2Ce480020%2Ce480023%2Ce480024%2Ce480027%2Ce480028%2Ce480029%2Ce48002f%2Ce480038%2Ce48003f%2Ce480062%2Ce4800c4%2Ce4800c7%2Ce4800c9%2Ce4800ca%2Ce4800cb%2Ce4800cd%2Ce4800cf%2Ce4800d0%2Ce4800d2%2Ce4800fa%2Ce480136%2Ce480138%2Ce480139%2Ce48016e%2Ce48016f%2Ce4801c7%2Ce500001%2Ce500002%2Ce500003%2Ce500005%2Ce500006%2Ce500007%2Ce50000a%2Ce50000b%2Ce50000c%2Ce50000d%2Ce50000e%2Ce50000f%2Ce500010%2Ce500011%2Ce500012%2Ce500013%2Ce500014%2Ce500015%2Ce500016%2Ce500017%2Ce500018%2Ce500019%2Ce50001a%2Ce50001b%2Ce50001c%2Ce50001d%2Ce50001e%2Ce50001f%2Ce500020%2Ce500021%2Ce500022%2Ce500023%2Ce500024%2Ce500025%2Ce500027%2Ce500028%2Ce500029%2Ce50002a%2Ce50002b%2Ce50002c%2Ce50002d%2Ce50002e%2Ce50002f%2Ce500030%2Ce500032%2Ce500034%2Ce500035%2Ce500037%2Ce500038%2Ce500039%2Ce50003a%2Ce50003b%2Ce50003c%2Ce50003d%2Ce50003e%2Ce50003f%2Ce500040%2Ce500041%2Ce500042%2Ce500043%2Ce500044%2Ce500045%2Ce50004a%2Ce50004e%2Ce500051%2Ce500058%2Ce50005c%2Ce500061%2Ce500063%2Ce50006b%2Ce50006e%2Ce50006f%2Ce500076%2Ce500077%2Ce500078%2Ce500079%2Ce50007a%2Ce50007b%2Ce50007e%2Ce500080%2Ce500082%2Ce500083%2Ce500084%2Ce50008b%2Ce50008c%2Ce50008f%2Ce500090%2Ce500092%2Ce500093%2Ce500094%2Ce500095%2Ce500096%2Ce500097%2Ce500098%2Ce500099%2Ce50009a%2Ce50009d%2Ce50009e%2Ce5000a0%2Ce5000a1%2Ce5000a2%2Ce5000a3%2Ce5000a4%2Ce5000a5%2Ce5000a6%2Ce5000a8%2Ce5000a9%2Ce5000aa%2Cfff40015%2Cfff8007f%2C40014d%2C400389%2C400ab1&mnonly=0&newproducts=0&ColumnSort=1000011&page=1&stock=1&quantity=0&ptm=0&fid=0&pageSize=250

I actually liked this option from AVX, which is small and fits the bill:

http://www.digikey.com/product-detail/en/avx-corporation/SD2114S040S8R0/478-7817-2-ND/3749521

However, maybe a more standard and bigger DO-214 (SMB or SMC) would be a better option, so we can change PN or manufacturer later.
